project_id = "xtyxukqjfziippvgjiur"

[functions.upload-submission-file]
verify_jwt = false

[functions.create-submission]
verify_jwt = false

[functions.detect-country]
verify_jwt = false

[functions.list-submissions-export]
verify_jwt = false

[functions.sign-submission-files]
verify_jwt = false
